ci:
  autoupdate_schedule: quarterly

exclude: |
  (?x)^(
    gsd.(?:c|h)|
    tests/catch.(?:cc|hpp)|
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/glotzerlab/fix-license-header
    rev: v0.4.1
    hooks:
      - id: fix-license-header
        types_or: [c, c++]
        args:
          - --license-file=LICENSE
          - --num=2
          - --add=Part of gsd-vmd, released under the BSD 3-Clause License.
          - --comment-prefix=//
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.2
    hooks:
      - id: clang-format
        types_or: [c, c++]
